#!/usr/bin/env bash
# =============================================================================
# AI Dashboard Agent – cross-platform service installer
# =============================================================================
# Linux:
#   - Ensures apt-installed agent binary exists
#   - Writes /etc/ai-dashboard-agent/agent.conf
#   - Enables + starts ai-dashboard-agent.service (systemd, auto-start on boot)
#
# macOS:
#   - Uses local source runner with an explicit Python interpreter
#   - Writes /etc/ai-dashboard-agent/agent.conf
#   - Installs + starts launchd daemon (auto-start on boot)
#
# Usage (interactive):
#   sudo bash install.sh
#
# Usage (non-interactive):
#   sudo AI_DASHBOARD_HOST=https://dash.example.com \
#        AI_DASHBOARD_USERNAME=admin \
#        AI_DASHBOARD_PASSWORD=secret \
#        bash install.sh
#
# Linux optional package source:
#   sudo AI_DASHBOARD_DEB=../ai-dashboard-agent_0.1.0-1_all.deb bash install.sh
#
# macOS optional Python interpreter:
#   sudo AI_DASHBOARD_PYTHON=/opt/homebrew/bin/python3 bash install.sh
# =============================================================================

set -euo pipefail

OS_NAME="$(uname -s)"
AGENT_SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SERVICE_NAME="ai-dashboard-agent"
CONF_DIR="/etc/ai-dashboard-agent"
CONF_FILE="${CONF_DIR}/agent.conf"
STATE_DIR="/var/lib/ai-dashboard-agent"

LINUX_DEB_PATH="${AI_DASHBOARD_DEB:-}"

MAC_LABEL="com.ai-dashboard.agent"
MAC_PLIST="/Library/LaunchDaemons/${MAC_LABEL}.plist"
MAC_RUNNER="/usr/local/bin/ai-dashboard-agent-source-runner"
MAC_PYTHON="${AI_DASHBOARD_PYTHON:-$(command -v python3 || true)}"

# ── Privilege check -----------------------------------------------------------
if [[ "${EUID}" -ne 0 ]]; then
    echo "ERROR: This installer must be run as root (use sudo)." >&2
    exit 1
fi

if [[ "${OS_NAME}" != "Linux" && "${OS_NAME}" != "Darwin" ]]; then
    echo "ERROR: Unsupported OS '${OS_NAME}'. Supported: Linux, macOS." >&2
    exit 1
fi

# ── Collect configuration -----------------------------------------------------
HOST="${AI_DASHBOARD_HOST:-}"
USERNAME="${AI_DASHBOARD_USERNAME:-}"
PASSWORD="${AI_DASHBOARD_PASSWORD:-}"
INTERVAL="${AI_DASHBOARD_INTERVAL:-2}"

if [[ -z "${HOST}" ]]; then
    read -rp "Dashboard URL (e.g. https://your-dashboard.example.com): " HOST
fi
if [[ -z "${USERNAME}" ]]; then
    read -rp "Dashboard username: " USERNAME
fi
if [[ -z "${PASSWORD}" ]]; then
    read -rsp "Dashboard password: " PASSWORD
    echo
fi

if [[ -z "${HOST}" || -z "${USERNAME}" || -z "${PASSWORD}" ]]; then
    echo "ERROR: Host, username, and password are all required." >&2
    exit 1
fi

HOST="${HOST%/}"

# ── Common config/state -------------------------------------------------------
install -d -m 750 "${CONF_DIR}"
install -d -m 750 "${STATE_DIR}"

cat > "${CONF_FILE}" <<EOF
# AI Dashboard Agent configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to change settings, then restart the agent service.

AI_DASHBOARD_HOST=${HOST}
AI_DASHBOARD_USERNAME=${USERNAME}
AI_DASHBOARD_PASSWORD=${PASSWORD}
AI_DASHBOARD_INTERVAL=${INTERVAL}
# AI_DASHBOARD_LOG_LEVEL=INFO
# AI_DASHBOARD_DISKS=sda,sdb
EOF

if [[ "${OS_NAME}" == "Darwin" ]]; then
    chown root:wheel "${CONF_FILE}"
else
    chown root:root "${CONF_FILE}"
fi
chmod 640 "${CONF_FILE}"
echo "Config written to ${CONF_FILE}"

# ── Linux path: apt + systemd ------------------------------------------------
if [[ "${OS_NAME}" == "Linux" ]]; then
    if ! command -v ai-dashboard-agent >/dev/null 2>&1; then
        if [[ -n "${LINUX_DEB_PATH}" ]]; then
            echo "Installing ai-dashboard-agent from ${LINUX_DEB_PATH} ..."
            apt install -y "${LINUX_DEB_PATH}"
        else
            echo "Installing ai-dashboard-agent from apt repositories ..."
            if ! apt install -y ai-dashboard-agent; then
                echo "ERROR: Could not install ai-dashboard-agent from apt." >&2
                echo "Provide AI_DASHBOARD_DEB=/path/to/ai-dashboard-agent_*_all.deb" >&2
                exit 1
            fi
        fi
    fi

    if ! AGENT_BIN="$(command -v ai-dashboard-agent 2>/dev/null)"; then
        echo "ERROR: ai-dashboard-agent binary not found after apt install." >&2
        exit 1
    fi
    echo "Agent binary: ${AGENT_BIN}"

    systemctl daemon-reload
    systemctl enable --now "${SERVICE_NAME}"

    echo ""
    echo "==================================================================="
    echo "  AI Dashboard Agent installed and started successfully (Linux)."
    echo "  Service   : ${SERVICE_NAME}.service"
    echo "  Config    : ${CONF_FILE}"
    echo "  State     : ${STATE_DIR}/state.json"
    echo "  Autostart : enabled (systemd)"
    echo ""
    echo "  Useful commands:"
    echo "    systemctl status ${SERVICE_NAME}"
    echo "    journalctl -u ${SERVICE_NAME} -f"
    echo "    systemctl restart ${SERVICE_NAME}"
    echo "==================================================================="
    exit 0
fi

# ── macOS path: source runner + launchd --------------------------------------
if [[ -z "${MAC_PYTHON}" ]]; then
    echo "ERROR: python3 not found." >&2
    echo "Set AI_DASHBOARD_PYTHON=/path/to/python3 and retry." >&2
    exit 1
fi

if ! PYTHONPATH="${AGENT_SOURCE_DIR}/src" "${MAC_PYTHON}" -c "import psutil, requests, ai_dashboard_agent" >/dev/null 2>&1; then
    echo "ERROR: Python environment is missing required modules for the agent." >&2
    echo "Use a prepared environment and pass AI_DASHBOARD_PYTHON, for example:" >&2
    echo "  sudo AI_DASHBOARD_PYTHON=/opt/homebrew/bin/python3 bash install.sh" >&2
    exit 1
fi

install -d -m 755 /usr/local/bin
cat > "${MAC_RUNNER}" <<EOF
#!/usr/bin/env bash
set -euo pipefail
export PYTHONPATH="${AGENT_SOURCE_DIR}/src\${PYTHONPATH:+:\$PYTHONPATH}"
exec "${MAC_PYTHON}" -m ai_dashboard_agent "\$@"
EOF
chmod 755 "${MAC_RUNNER}"
chown root:wheel "${MAC_RUNNER}"

cat > "${MAC_PLIST}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${MAC_LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>${MAC_RUNNER}</string>
    <string>--config</string>
    <string>${CONF_FILE}</string>
    <string>--quiet</string>
  </array>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>${AGENT_SOURCE_DIR}</string>
  <key>StandardOutPath</key>
  <string>/var/log/ai-dashboard-agent.log</string>
  <key>StandardErrorPath</key>
  <string>/var/log/ai-dashboard-agent.err.log</string>
</dict>
</plist>
EOF

chmod 644 "${MAC_PLIST}"
chown root:wheel "${MAC_PLIST}"

# Replace existing service definition (if any), then load + start.
launchctl bootout system "${MAC_PLIST}" >/dev/null 2>&1 || true
launchctl bootstrap system "${MAC_PLIST}"
launchctl enable "system/${MAC_LABEL}"
launchctl kickstart -k "system/${MAC_LABEL}"

echo ""
echo "==================================================================="
echo "  AI Dashboard Agent installed and started successfully (macOS)."
echo "  Service   : ${MAC_LABEL}"
echo "  Config    : ${CONF_FILE}"
echo "  State     : ${STATE_DIR}/state.json"
echo "  Autostart : enabled (launchd)"
echo ""
echo "  Useful commands:"
echo "    launchctl print system/${MAC_LABEL}"
echo "    launchctl kickstart -k system/${MAC_LABEL}"
echo "    sudo tail -f /var/log/ai-dashboard-agent.log"
echo "==================================================================="
