#!/usr/bin/env bash
# =============================================================================
# AI Dashboard Agent – systemd service installer
# =============================================================================
# Usage (interactive):
#   sudo bash install.sh
#
# Usage (non-interactive / scripted):
#   sudo AI_DASHBOARD_HOST=https://dash.example.com \
#        AI_DASHBOARD_USERNAME=admin \
#        AI_DASHBOARD_PASSWORD=secret \
#        bash install.sh
#
# What this script does
# ---------------------
# 1. Installs the ai-dashboard-agent Python package via pip.
# 2. Creates /etc/ai-dashboard-agent/agent.conf with the supplied credentials.
# 3. Writes /etc/systemd/system/ai-dashboard-agent.service.
# 4. Enables and starts the service (runs on every boot).
#
# Idempotent: safe to run multiple times on the same machine.
# The agent will always register as the same server entry on the dashboard
# because it identifies itself by /etc/machine-id.
# =============================================================================

set -euo pipefail

AGENT_PACKAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="ai-dashboard-agent"
CONF_DIR="/etc/ai-dashboard-agent"
CONF_FILE="${CONF_DIR}/agent.conf"
STATE_DIR="/var/lib/ai-dashboard-agent"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

# ── Privilege check -----------------------------------------------------------
if [[ "${EUID}" -ne 0 ]]; then
    echo "ERROR: This installer must be run as root (use sudo)." >&2
    exit 1
fi

# ── Collect configuration -----------------------------------------------------
HOST="${AI_DASHBOARD_HOST:-}"
USERNAME="${AI_DASHBOARD_USERNAME:-}"
PASSWORD="${AI_DASHBOARD_PASSWORD:-}"
INTERVAL="${AI_DASHBOARD_INTERVAL:-2}"
PYTHON="${PYTHON:-$(command -v python3 || true)}"

if [[ -z "${HOST}" ]]; then
    read -rp "Dashboard URL (e.g. https://your-dashboard.example.com): " HOST
fi
if [[ -z "${USERNAME}" ]]; then
    read -rp "Dashboard username: " USERNAME
fi
if [[ -z "${PASSWORD}" ]]; then
    read -rsp "Dashboard password: " PASSWORD
    echo
fi

if [[ -z "${HOST}" || -z "${USERNAME}" || -z "${PASSWORD}" ]]; then
    echo "ERROR: Host, username, and password are all required." >&2
    exit 1
fi

# Strip trailing slash
HOST="${HOST%/}"

# ── Find Python ---------------------------------------------------------------
if [[ -z "${PYTHON}" ]]; then
    echo "ERROR: python3 not found. Install Python 3.10+ and re-run." >&2
    exit 1
fi

PYTHON_VERSION=$("${PYTHON}" -c "import sys; print('%d.%d' % sys.version_info[:2])")
echo "Using Python ${PYTHON_VERSION} at ${PYTHON}"

# ── Install the agent package -------------------------------------------------
echo ""
echo "Installing ai-dashboard-agent ..."
"${PYTHON}" -m pip install --quiet --upgrade "${AGENT_PACKAGE_DIR}"

AGENT_BIN=$(command -v ai-dashboard-agent 2>/dev/null || \
    "${PYTHON}" -c "import shutil, sys; b=shutil.which('ai-dashboard-agent'); print(b or '')")

if [[ -z "${AGENT_BIN}" ]]; then
    # Try the user/local bin paths pip may have used
    for candidate in \
        /usr/local/bin/ai-dashboard-agent \
        "${HOME}/.local/bin/ai-dashboard-agent" \
        "$("${PYTHON}" -c "import sysconfig; print(sysconfig.get_path('scripts'))" 2>/dev/null || true)/ai-dashboard-agent"; do
        if [[ -x "${candidate}" ]]; then
            AGENT_BIN="${candidate}"
            break
        fi
    done
fi

if [[ -z "${AGENT_BIN}" ]]; then
    echo "ERROR: ai-dashboard-agent binary not found after install." >&2
    echo "Ensure pip scripts directory is on PATH and retry." >&2
    exit 1
fi
echo "Agent binary: ${AGENT_BIN}"

# ── Create directories --------------------------------------------------------
install -d -m 750 "${CONF_DIR}"
install -d -m 750 "${STATE_DIR}"

# ── Write config file ---------------------------------------------------------
cat > "${CONF_FILE}" <<EOF
# AI Dashboard Agent configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to change settings, then: systemctl restart ${SERVICE_NAME}

AI_DASHBOARD_HOST=${HOST}
AI_DASHBOARD_USERNAME=${USERNAME}
AI_DASHBOARD_PASSWORD=${PASSWORD}
AI_DASHBOARD_INTERVAL=${INTERVAL}
# AI_DASHBOARD_LOG_LEVEL=INFO
# AI_DASHBOARD_DISKS=sda,sdb
EOF
chmod 640 "${CONF_FILE}"
echo "Config written to ${CONF_FILE}"

# ── Write systemd unit --------------------------------------------------------
cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=AI Dashboard Agent
Documentation=https://github.com/dsrivastavv/AI-Dashboard
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
ExecStart=${AGENT_BIN} --config ${CONF_FILE} --quiet
Restart=on-failure
RestartSec=10s

# Drop privileges
User=root
# Optionally run as a dedicated user by creating one and chown-ing the dirs:
#   useradd -r -s /usr/sbin/nologin aidashboard
#   chown -R aidashboard: /etc/ai-dashboard-agent /var/lib/ai-dashboard-agent
# Then set:
#   User=aidashboard

# Basic sandboxing
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=${STATE_DIR}
PrivateTmp=true
NoNewPrivileges=true

# Logging (journald captures stdout/stderr automatically)
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

[Install]
WantedBy=multi-user.target
EOF
echo "Service unit written to ${SERVICE_FILE}"

# ── Enable and start ----------------------------------------------------------
systemctl daemon-reload
systemctl enable --now "${SERVICE_NAME}"

echo ""
echo "==================================================================="
echo "  AI Dashboard Agent installed and started successfully."
echo ""
echo "  Dashboard : ${HOST}"
echo "  Service   : ${SERVICE_NAME}"
echo "  Config    : ${CONF_FILE}"
echo "  State     : ${STATE_DIR}/state.json  (token cache)"
echo ""
echo "  Useful commands:"
echo "    systemctl status ${SERVICE_NAME}"
echo "    journalctl -u ${SERVICE_NAME} -f"
echo "    systemctl restart ${SERVICE_NAME}"
echo "    bash uninstall.sh   (to remove)"
echo "==================================================================="
