# Generated by Django 6.0.2 on 2026-02-26 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('interval_seconds', models.FloatField(blank=True, null=True)),
                ('cpu_usage_percent', models.FloatField(default=0)),
                ('cpu_user_percent', models.FloatField(blank=True, null=True)),
                ('cpu_system_percent', models.FloatField(blank=True, null=True)),
                ('cpu_iowait_percent', models.FloatField(blank=True, null=True)),
                ('cpu_load_1', models.FloatField(blank=True, null=True)),
                ('cpu_load_5', models.FloatField(blank=True, null=True)),
                ('cpu_load_15', models.FloatField(blank=True, null=True)),
                ('cpu_frequency_mhz', models.FloatField(blank=True, null=True)),
                ('cpu_count_logical', models.IntegerField(default=0)),
                ('cpu_count_physical', models.IntegerField(blank=True, null=True)),
                ('memory_total_bytes', models.BigIntegerField(default=0)),
                ('memory_used_bytes', models.BigIntegerField(default=0)),
                ('memory_available_bytes', models.BigIntegerField(default=0)),
                ('memory_percent', models.FloatField(default=0)),
                ('swap_total_bytes', models.BigIntegerField(default=0)),
                ('swap_used_bytes', models.BigIntegerField(default=0)),
                ('swap_percent', models.FloatField(default=0)),
                ('disk_read_bps', models.FloatField(default=0)),
                ('disk_write_bps', models.FloatField(default=0)),
                ('disk_read_iops', models.FloatField(default=0)),
                ('disk_write_iops', models.FloatField(default=0)),
                ('disk_util_percent', models.FloatField(default=0)),
                ('disk_avg_util_percent', models.FloatField(default=0)),
                ('network_rx_bps', models.FloatField(default=0)),
                ('network_tx_bps', models.FloatField(default=0)),
                ('network_rx_bytes_total', models.BigIntegerField(default=0)),
                ('network_tx_bytes_total', models.BigIntegerField(default=0)),
                ('process_count', models.IntegerField(default=0)),
                ('gpu_present', models.BooleanField(default=False)),
                ('gpu_count', models.IntegerField(default=0)),
                ('top_gpu_util_percent', models.FloatField(blank=True, null=True)),
                ('avg_gpu_util_percent', models.FloatField(blank=True, null=True)),
                ('top_gpu_memory_percent', models.FloatField(blank=True, null=True)),
                ('avg_gpu_memory_percent', models.FloatField(blank=True, null=True)),
                ('bottleneck', models.CharField(default='unknown', max_length=32)),
                ('bottleneck_confidence', models.FloatField(default=0)),
                ('bottleneck_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['-collected_at'], name='monitoring__collect_f19774_idx'), models.Index(fields=['bottleneck', '-collected_at'], name='monitoring__bottlen_b2eaaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='GpuMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_index', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('uuid', models.CharField(blank=True, max_length=128)),
                ('utilization_gpu_percent', models.FloatField(blank=True, null=True)),
                ('utilization_memory_percent', models.FloatField(blank=True, null=True)),
                ('memory_total_bytes', models.BigIntegerField(default=0)),
                ('memory_used_bytes', models.BigIntegerField(default=0)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('power_w', models.FloatField(blank=True, null=True)),
                ('power_limit_w', models.FloatField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='monitoring.metricsnapshot')),
            ],
            options={
                'ordering': ['gpu_index'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'gpu_index'), name='uniq_gpu_metric_per_snapshot_index')],
            },
        ),
        migrations.CreateModel(
            name='DiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=64)),
                ('read_bytes_total', models.BigIntegerField(default=0)),
                ('write_bytes_total', models.BigIntegerField(default=0)),
                ('read_count_total', models.BigIntegerField(default=0)),
                ('write_count_total', models.BigIntegerField(default=0)),
                ('busy_time_ms_total', models.BigIntegerField(blank=True, null=True)),
                ('read_bps', models.FloatField(default=0)),
                ('write_bps', models.FloatField(default=0)),
                ('read_iops', models.FloatField(default=0)),
                ('write_iops', models.FloatField(default=0)),
                ('util_percent', models.FloatField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='monitoring.metricsnapshot')),
            ],
            options={
                'ordering': ['device'],
                'indexes': [models.Index(fields=['device', 'snapshot'], name='monitoring__device_36dd47_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'device'), name='uniq_disk_metric_per_snapshot_device')],
            },
        ),
    ]
