# Generated by Django 6.0.2 on 2026-02-26 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('api_token_hash', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_agent_version', models.CharField(blank=True, max_length=64)),
                ('agent_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name', 'slug'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='monitoring__is_acti_aa58bb_idx'), models.Index(fields=['-last_seen_at'], name='monitoring__last_se_737bc2_idx')],
            },
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitoring.monitoredserver'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['server', 'collected_at'], name='monitoring__server__fa0410_idx'),
        ),
    ]
