# Generated by Django 6.0.2 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_monitoredserver_metricsnapshot_server_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsnapshot",
            name="cpu_temperature_c",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
