# Generated by Django 6.0.2 on 2026-02-28 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_metricsnapshot_cpu_temperature_c"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsnapshot",
            name="fan_avg_rpm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="fan_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="metricsnapshot",
            name="fan_max_rpm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FanMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=64)),
                ("speed_rpm", models.IntegerField(default=0)),
                ("snapshot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fans", to="monitoring.metricsnapshot")),
            ],
            options={
                "ordering": ["label"],
                "constraints": [
                    models.UniqueConstraint(fields=("snapshot", "label"), name="uniq_fan_metric_per_snapshot_label")
                ],
            },
        ),
        migrations.AddField(
            model_name="gpumetric",
            name="fan_speed_percent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
