# Generated by Django 6.0.2 on 2026-02-28 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_fanmetric_and_snapshot_fans"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.CharField(choices=[("info", "Info"), ("warning", "Warning"), ("critical", "Critical")], default="info", max_length=16)),
                ("code", models.CharField(blank=True, db_index=True, max_length=64)),
                ("title", models.CharField(max_length=128)),
                ("message", models.CharField(blank=True, max_length=512)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("server", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="monitoring.monitoredserver")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at", "is_read"], name="monitoring__create_5ce5e3_idx"),
                    models.Index(fields=["code", "-created_at"], name="monitoring__code_ddd9ae_idx"),
                ],
            },
        ),
    ]
